package com.example.navdeep_bilin_myruns3.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "exercise_entries")
data class ExerciseEntryEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0L, // autogenerated ID key
    val inputType: Int,          // 0 manual, 1 GPS, 2 automatic
    val activityType: Int,       // running, cycling, etc.
    val dateTimeMillis: Long,    // epoch millis
    val durationSec: Double,     // seconds
    val distanceMeters: Double,  // meters
    val calorie: Double?,
    val climbMeters: Double?,    // meters
    val heartRate: Double?,
    val comment: String?,
    val locationBlob: ByteArray? // keep for MR4, can be null in MR3
)




// * Primary key:
// *  - id (autoGenerated)
// *
// * Storage convention:
// *  - distance is stored in meters regardless of user unit preference.
// *  - duration is stored in seconds.
// *  - dateTimeMillis is epoch millis.
// *  - optional fields use nullable types.
